apiVersion: v1
kind: Service
metadata:
  name: one-sb-motor-demo-svc
  namespace: insurance-demo
spec:
  selector:
    app: one-sb-motor-demo
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
