apiVersion: apps/v1
kind: Deployment
metadata:
  name: one-sb-demo
  namespace: insurance-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: one-sb-demo
  template:
    metadata:
      labels:
        app: one-sb-demo
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: onsurityk8s
      imagePullSecrets:
        - name: ecr-registry-secret
      nodeSelector:
        node-role: worker-1
      containers:
        - name: one-sb-demo
          image: 106102357433.dkr.ecr.ap-south-1.amazonaws.com/one-sb-demo:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: env-uat-cm
          readinessProbe:
            httpGet:
              path: /v2/healthcheck
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /v2/healthcheck
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "600m"
              memory: "512Mi"