apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-one-sb-demo
  namespace: insurance-demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: uat-api.insurance.onsurity.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: one-sb-demo-svc
                port:
                  number: 80
                  