apiVersion: v1
kind: Service
metadata:
  name: one-sb-health-demo-svc
  namespace: insurance-demo
spec:
  selector:
    app: one-sb-health-demo
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
# NOTE: change to NodePort and set nodePort if you want nginx to route directly to node ports.
